Transform decomposition into translation/rotation/skew/scale
BrainiumLLC/gee pull request #4
Opened 2021-03-11 19:37 UTC by unconed

Transform:
- Add a `decompose()` and `from_decomposition(...)`
- Add a `from_skew(...)`, `pre_skew(...)` and `post_skew(...)`. The skew angle is the rotation of Y relative to 90º from X.
- Add tests

2021-03-11 21:17 UTC, unconed commented
I cleaned up the T::zero() usage.

2021-03-11 21:46 UTC, francesca64 requested changes
Looks great, and thanks for adding tests!

2021-03-11 21:46 UTC, francesca64 commented on src/transform.rs
> +        let c1 = rotation.cos();
I feel this would be cuter:
```suggestion
        let (s1, c1) = rotation.sin_cos();
```
(especially for the `s2`/`c2` below)

2021-03-11 21:46 UTC, francesca64 commented on src/transform.rs
> +    pub fn from_decomposition(
Having `decompose` below `inverse` makes sense to me, but `from_decomposition` would probably fit best as the last `from_*` method (right above `determinant`)

2021-04-01 21:42 UTC, francesca64 approved these changes
Thanks!

2021-04-01 22:04 UTC, merged